import { Coffee } from '../contexts/CoffeeContext'

export const startingCoffees: Coffee[] = [
  {
    id: 1,
    name: 'Expresso Tradicional',
    description: 'O tradicional feito com água quente e grãos moídos',
    price: 7.9,
    imageSrc: '/coffees/tradicional.png',
    tags: ['tradicional'],
    amount: 0,
  },
  {
    id: 2,
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 7,
    imageSrc: '/coffees/americano.png',
    tags: ['tradicional'],
    amount: 0,
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 8.5,
    imageSrc: '/coffees/cremoso.png',
    tags: ['tradicional'],
    amount: 0,
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso com cubos de gelo',
    price: 7.9,
    imageSrc: '/coffees/gelado.png',
    tags: ['tradicional', 'gelado'],
    amount: 0,
  },
  {
    id: 5,
    name: 'Café com leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 7.9,
    imageSrc: '/coffees/leite.png',
    tags: ['tradicional', 'com leite'],
    amount: 0,
  },
  {
    id: 6,
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de ledite e espuma cremosa',
    price: 8.9,
    imageSrc: '/coffees/latte.png',
    tags: ['tradicional', 'com leite'],
    amount: 0,
  },
  {
    id: 7,
    name: 'Capuccino ',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 8.9,
    imageSrc: '/coffees/capuccino.png',
    tags: ['tradicional', 'com leite'],
    amount: 0,
  },
  {
    id: 8,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 8.9,
    imageSrc: '/coffees/machiatto.png',
    tags: ['tradicional', 'com leite'],
    amount: 0,
  },
  {
    id: 9,
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 8.9,
    imageSrc: '/coffees/mocaccino.png',
    tags: ['tradicional', 'com leite'],
    amount: 0,
  },
  {
    id: 10,
    name: 'Chocolate quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 10,
    imageSrc: '/coffees/chocolate_quente.png',
    tags: ['especial', 'com leite'],
    amount: 0,
  },
  {
    id: 11,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
    imageSrc: '/coffees/cubano.png',
    tags: ['especial', 'alcoólico', 'gelado'],
    amount: 0,
  },
  {
    id: 12,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
    imageSrc: '/coffees/havaiano.png',
    tags: ['especial'],
    amount: 0,
  },
  {
    id: 13,
    name: 'Árabe',
    description: 'bebida preparada com grãos de café árabe e especiarias',
    price: 10.5,
    imageSrc: '/coffees/arabe.png',
    tags: ['especial'],
    amount: 0,
  },
  {
    id: 14,
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
    imageSrc: '/coffees/irlandes.png',
    tags: ['especial', 'alcoólico'],
    amount: 0,
  },
]
